name: build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Enable Git support for long file paths
        run: git config --system core.longpaths true
      - name: Set up directories
        run: "md -Path 'C:\\moon\\randomizer'"
      - name: Extract tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v?([^-]*)"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install MSVC developer tools
        uses: microsoft/setup-msbuild@v1.1
        with:
          arch: x64
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"
      - name: Generate solution
        shell: cmd
        run: |
          gen_win64_vs2022.release.bat
          IF ERRORLEVEL 1 (
            echo GENERATING FAILED
            exit 1
          )
      - name: Compile Wotw Rando
        shell: cmd
        run: |
          cmake --build .\build\win64 --target INSTALL_RUNTIME --config RelWithDebInfo
          IF ERRORLEVEL 1 (
            echo BUILD FAILED
            exit 1
          )
      - name: Archive randomizer
        uses: actions/upload-artifact@v2
        with:
          name: randomizer
          path: 'C:\moon\randomizer\*'
