name: build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022

    env:
      WORKDIR: D:/build
      SCCACHE_GHA_ENABLED: "true"

    steps:
      - name: Enable Git support for long file paths
        run: git config --system core.longpaths true
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Set up directories
        run: "md -Path 'C:\\moon\\randomizer'"
      - name: Extract tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v?([^-]*)"
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install MSVC developer tools
        uses: microsoft/setup-msbuild@v1.1
        with:
          arch: x64
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.62.0
      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"
      - name: Symlink build directory
        run: |
          $path = Resolve-Path .
          New-Item -Path ${{ env.WORKDIR }} -ItemType SymbolicLink -Value $path
      - name: Generate solution
        shell: cmd
        working-directory: ${{ env.WORKDIR }}
        run: |
          gen_win64_vs2022.release.bat
          IF ERRORLEVEL 1 (
            echo GENERATING FAILED
            exit 1
          )
      - name: Compile Wotw Rando
        shell: cmd
        working-directory: ${{ env.WORKDIR }}
        run: |
          cmake --build cmake-build-relwithdebinfo --target INSTALL_RUNTIME --config RelWithDebInfo -- -clp:ForceConsoleColor
          IF ERRORLEVEL 1 (
            echo BUILD FAILED
            exit 1
          )
      - name: Archive randomizer
        uses: actions/upload-artifact@v2
        with:
          name: randomizer
          path: 'C:\moon\randomizer\*'
